services:
  mongodb-nest:
      image: mongo
      container_name: mongodb-nest
      restart: always
      command: ["--port", "3000"]
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
        MONGO_INITDB_DB_NAME: ${DB_NAME}
      ports:
        - '9000:27017'
      volumes:
        - dbdata:/data/db
      env_file:
        - .env
      networks:
        - nest_net
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongosh --quiet --host  mongodb-nest:9000
        interval: 10s
        timeout: 5s
        retries: 5


volumes:
  dbdata: {}

